project:
  type: website
  output-dir: docs

website:
  title: "Solutions Library"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Articles"
        menu:
          - notebooks/y-axis-lollipop.qmd
          - notebooks/reshape-combine-multiple-df-long-format.qmd

format:
  html:  
    theme: default  # Can be changed to "cosmo", "darkly", "flatly", etc.
    toc: true
    code-overflow: wrap
    code-tools: true
    code-fold: true
    code-summary: "Show code"
